---
title: "Historical Epidemiological Data"
output: rmarkdown::html_vignette
bibliography: references.bib
csl: nature.csl
link-citations: true
vignette: >
  %\VignetteIndexEntry{Historical Epidemiological Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(site)
```

## Cases and deaths

`site_file$cases_deaths`

World Malaria Report cases and deaths estimates.

### Variables
`wmr_cases_l` WMR case estimate, lower bound  
`wmr_cases` WMR case point estimate  
`wmr_cases_u` WMR case estimate, upper bound  
`wmr_deaths_l` WMR death estimate, lower bound  
`wmr_deaths` WMR death point estimate  
`wmr_deaths_u` WMR death estimate, upper bound  
`wmr_par` WMR population at risk estimates
`wmr_incidence_l` WMR case incidence estimate, lower bound  
`wmr_incidence` WMR case incidence point estimate  
`wmr_incidence_u` WMR case incidence estimate, upper bound  
`wmr_mortality_l` WMR malaria mortality rate estimate, lower bound  
`wmr_mortality` WMR malaria mortality rate point estimate  
`wmr_mortality_u` WMR malaria mortality rateestimate, upper bound  

### Description

Time series take all information from the most recent WMR. Older entries are from previous editions of the WMR.

### Sources
`r who_badge()`

## Prevalence

`site_file$prevalence`

Plasmodium falciparum and Plasmodium vivax prevalence estimates

### Variables
`pfpr` Plasmodium falciparum parasite prevalence in 2-10 year olds  
`pvpr` Plasmodium vivax parasite prevalence in 1-99 year olds

### Description

Pixel-level estimates of prevalence indicators are agregated at the site-level by taking the population at risk weighted average.

Prevalence estimates are used for calibrating the baseline EIR using the [cali package](https://mrc-ide.github.io/cali/).

### Sources

`r map_badge()`
