---
title: "Interventions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Interventions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(site)
```

Interventions contains the historical intervention information for a site. It is also the section of the site file that you would modify with intervention information for future scenarios. Details, references and methods for individual interventions are shown below:

Note on time: The model assumes all years have 365 days (no leap years). Intervention time points are therefore specified using a `year` column plus a "day_of_year" column, where day of year runs from 1 to 365 inclusive.

## ITNs

`site_file$interventions$itn$implementation`

Bed net implementation details

### Variables
`net_type` Type of net  
`distribution_type` Type of net distribution, mass-campaign or routine  
`distribution_day_of_year` Day of the year for the distribution  
`distribution_lower` Lower bound for possible itn_input_dist  
`distribution_upper` Upper bound for possible itn_input_dist

### Description
Supported net types currently include: "pyrethroid_only", "pyrethroid_pbo", "pyrethroid_pyrrole". Net type introductions are informed by data from the Alliance for Malaria Prevention. Current available net types are: pyrethroid_only, pyrethroid_pbo and pyrethroid_pyrrole. Absent systematic, country data on mass campaign dates and locations we assume that mass campaigns occur on the
first day of the year and routine distributions occur quarterly. Lower and upper bounds help to ensure that
sensible model input distributions are estimated, see `stop_missing_itn_input_dist()` for full details. Due to differences in the availability of data sources the approach for countries within sub-Saharan Africa differs to countries outside of sub-Saharan Africa:

**Within sub-Saharan Africa:** The population at risk weighted mean ITN use estimates for each site are taken 
from the malaria atlas project.

**Outside of sub-Saharan Africa:** ITN use is much more heterogeneous outside of SSA and data are less systematically collected. As a result, there are strong assumptions associated with the historical scale and magnitude of ITN distributions. We make the assumption that any reported ITN distributions (as detailed by the world malaria report) are targeted such that areas with the highest baseline prevalence are prioritised first. Net use is implemented up to a maximum usage of 55% in each area, sequentially working through the targeting until the reported total number of bed nets have been allocated.

Available data on ITN use will not extend to the present year. Missing ITN use estimates to present are filled assuming a constant, continuing level of coverage. To respect the multi-year cyclical nature of ITN distribution cycles any missing estimates are filled in assuming that coverage is constant with respect to 3 years prior. For example if years 2024, 2025 and 2026 are missing then 2024 == 2021, 2025 == 2022 and 2026 == 2023.

⚠️ **Warning:** For ITNs to work when passed to `site::site_parameters()` you will need to specify a column: `site_file$interventions$itn$implementation$itn_input_dist` indicating the size of the model ITN distributions each year. This is **not** the same as ITN usage. Use `site::site_usage_to_model_distribution()` to convert usage to model input distributions, or call `stop_missing_itn_input_dist()` for full details.

Given an ITN type and level of pyrethroid insecticide resistance, the site package will link to
corresponding estimates of the key ITN efficacy parameters.

### Sources
`r map_badge()`
`r who_badge()`
`r vectors_badge()`

---

`site_file$interventions$itn$use`

Bed net usage estimates

### Variables
`itn_use` ITN use  
`usage_day_of_year` Assumed day of the year at which usage was measured

### Description
Population at risk weighted average ITN use for each region. Usage measurements are assumed to occur on
the first day of the year (aligns with the MAP net online model).

### Sources
`r map_badge()`

---

`site_file$interventions$itn$retention_half_life`

ITN retention half-life

### Variable
`retention_half_life` Median retention half-life (days)

### Description
Retention half-life of nets in the population.

### Sources
`r vectors_badge()`

## IRS

`site_file$interventions$irs$implementation`

IRS implementation details

### Variables
`irs_cov` IRS coverage  
`peak_season` Rainfall seasonal peak day of the year  
`insecticide` IRS insecticide  
`round` Spray round  
`spray_day_of_year` Day of year of spray round  

### Description

As with ITNs, due to differences in the availability of data sources the approach 
for countries within sub-Saharan Africa differs to countries outside of 
sub-Saharan Africa:

**Within sub-Saharan Africa:** The population at risk weighted mean IRS coverage estimates for each spatial unit are summarised from the malaria atlas project

**Outside of sub-Saharan Africa:** IRS coverage is much more heterogeneous outside of SSA and data are less systematically collected. As a result, there are strong assumptions associated with the historical
scale and magnitude of IRS campaigns. We make the assumption that any reported
persons protected by IRS (as detailed by the world malaria report) are targeted such that
areas with the highest baseline prevalence are prioritised first. IRS coverage  
implemented up to a maximum usage of 80% in each area, sequentially working through
the targeting until the reported total number of persons protected have been allocated.

It is assumed that a DDT-type insecticide is used prior to 2017, after which
there is a switch to an actellic-like insecticide. Current available IRS insecticide options are: "ddt", "actellic", "bendiocarb" and "sumishield". We assume a single IRS spray round per year.

Given an IRS type and level of pyrethroid insecticide resistance, the site package will link to
corresponding estimates of the key ITN efficacy parameters.

Available data on IRS coverage (via MAP or the world malaria report) will not extend
to the present year. Missing IRS coverage estimates to present are filled assuming a
constant, continuing level of coverage.

### Sources
`r map_badge()`
`r who_badge()`

## Treatment

`site_file$interventions$treatment$implementation`

Treatment implementation details

### Variables
`year` Year at which coverage changes  
`day_of_year` Day of the year at which coverage changes  
`tx_cov` Effective treatment coverage  
`prop_act` Proportion of first line treatments that are an ACT

### Description
The population at risk weighted mean effective treatment coverage estimates for each spatial unit are summarised from the malaria atlas project. Note, as this metric describes "effective" treatment, we implement specifically parameterised drugs in the site file with efficacy = 1. For the proportion of treatments that are an ACT, for SSA estimates by year are expanded by linear interpolation between data 
points and an assumption of constant coverage after the most recent data point. 
We assume that ACT coverage is zero before 2006, when the WHO recommendation was 
first issued. For outside of SSA the DHS indicator is confounded by treatment 
for Plasmodium vivax, and we therefore assume the mean values by year from data 
within SSA. 

### Sources
`r map_badge()`
`r dhs_badge()`

---

`site_file$interventions$treatment$prop_public`

Proportion of treatments in the public sector

### Variables
`prop_public` Proportion of treatments in the public sector

### Description
This is useful for costing. We assume a constant proportion over time by country, estimated as the mean from all country survey estimates since 2010. For countries without survey data, we 
assume the median across all estimates.

### Sources
`r dhs_badge()`

## Seasonal malaria chemoprevention (SMC)

`site_file$interventions$smc$implementation`

SMC implementation details

### Variables
`smc_cov` SMC coverage  
`peak_season` Rainfall seasonal peak day of the year  
`smc_min_age` Lower bound of SMC-eligibility age range (days)  
`smc_max_age` Upper bound of SMC-eligibility age range (days)  
`round` Delivery round  
`round_day_of_year` Day of year each round is delivered  

### Description

Historical SMC implementation and coverage estimates are fragmented. We 
identify historical SMC implementation areas from maps presented by both
Access SMC and more recently 
SMC alliance. We assume a linear increase in 
coverage post implementation initiation up to a maximum of 80% to capture an 
increasing number of smaller sub-national units being targeted over time. We assume 4 rounds, centred on the seasonal peak in rainfall.

### Sources
`r smc_badge()`

---

`site_file$interventions$smc$drug`

SMC drug

### Variables
`drug` smc drug

### Description
We assume that SP-AQ is used for SMC. This is currently the only available drug
option.

### Sources
`r who_badge()`

## Vaccine

`site_file$interventions$vaccine$implementation`

Vaccine implementation details

### Variables
`year` Year at which coverage changes  
`day_of_year` Day of the year at which coverage changes  
`r21_primary_cov` Coverage of R21 primary series  
`rtss_primary_cov` Coverage of RTS,S primary series  
`peak_season` Rainfall seasonal peak day of the year  
`r21_booster1_cov` Coverage of the R21 first booster  
`rtss_booster1_cov` Coverage of the RTS,S first booster

### Description

We include historical RTS,S coverage that has occurred as part of the MVIP
implementation trial, sub-nationally in Malawi, Ghana and Kenya. The spatial
distribution is informed from an 
MVIP briefing presentation.

EPI-based vaccine scale up of R21 and RTS,S has been manually collated from
the UNICEF immunization dashboard. Absent sub-national data, the total doses delivered is converted into a country-wide coverage.

### Sources
`r who_badge()`
`r unicef_badge()`

---

`site_file$interventions$vaccine$delivery`

Vaccine delivery mode

### Variables
`delivery` Delivery mode

### Description
Can be age-based or hybrid (seasonal boosters)

### Sources
`r who_badge()`

---

`site_file$interventions$vaccine$primary_schedule`

Vaccine primary schedule ages

### Variables
`primary_schedule` Ages of 3 primary schedule doses (days)

### Description
Vaccines are assumed to have a primary schedule of 3-doses. Efficacy is assumed to start on receipt of the 3rd dose. 

### Sources
`r unicef_badge()`

---

`site_file$interventions$vaccine$booster_spacing`

Vaccine booster ages

### Variables
`booster_spacing` Vector of booster spacing

### Description
For age-based delivery booster timing is calculated relative to when an individual completes their primary vaccine series (after the third dose). If delivery is hybrid, the first booster spacing timestep is relative to the start of the year, otherwise they are relative to the last primary dose.

### Sources
`r unicef_badge()`

## Perennial malaria chemoprevention (PMC)

`site_file$interventions$pmc$implementation`

PMC implementation information

### Variables
`year` Year at which coverage changes  
`day_of_year` Day of the year at which coverage changes  
`pmc_cov` PMC coverage

### Description
This intervention has been known in the past as intermittent preventative treatment
of infants (IPTi). Due to the very limited (non-trial setting) implementation of PMC historically,
we mostly assume 0 coverage.

---

`site_file$interventions$pmc$drug`

PMC drug

### Variables
`drug` PMC drug

### Description
We assume PMC would be implemented with SP. This is currently the only available 
drug option.

### Sources
`r who_badge()`

---

`site_file$interventions$pmc$age`

### Variables
`age` Ages of 3 doses of PMC (days)

### Description
Assumed an age-based delivery through EPI 

### Sources
`r who_badge()`

---

## Larval source management

`site_file$interventions$lsm$implementation`

Larval source management

### Variables
`year` Year at which coverage changes  
`day_of_year` Day of the year at which coverage changes  
`lsm_cov` Proportion of breeding sites removed

### Description
Assumed 0 coverage. 
