---
title: "Metadata"
output: rmarkdown::html_vignette
bibliography: references.bib
csl: nature.csl
link-citations: true
vignette: >
  %\VignetteIndexEntry{Metadata}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Country

`site_file$metadata$country`

Country name

`site_file$metadata$iso3c`

The ISO3c code identifying the country. The R package `countrycode` @countrycode
is useful for converting between ISO3c and country names.

## Boundary

`site_file$metadata$boundary`

The boundary file version used to create sites

## Resolution

`site_file$metadata$admin_level`

The administrative levels (e.g. state, region, province) of the sites within the site file.

## Version

`site_file$metadata$version`

Site file version name. Please see the (change log)[https://mrc-ide.github.io/site/news/index.html] for version information.


## Sites

`site_file$sites`

The sites within the site file. These are the named sites disaggregated to the
specified administrative level. Further disaggregation may include, for example,
an [urban rural split](https://mrc-ide.github.io/site/articles/pop_demog.html).
We use the GADM @GADM 
version 4.1.0 administrative boundary simple feature spatial files at the first 
or second administrative unit level.

## Citations
