---
title: "Population and Demography"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Population and Demography}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(site)
```

## Population projections

`site_file$population$population_total`

Total population and population at risk estimates.

`site_file$population$population_by_age`

Single-year age disaggregated population and population at risk estimates.

### Variables

`pop` Total population  
`par` Total population at risk  
`par_pf` Total population at risk  
`par_pv` Total population at risk  
`age_lower` Age lower bound (years)  
`age_upper` Age upper bound (years)

### Description

Population total and age-disaggregated estimates by year for the country are sourced from the UN WPP. The spatial distribution of the population is informed using WorldPop population rasters. The spatial distribution pre-2015 and post-2026 is assumed to be that of 2015 and 2026 respectively. If the sitefile contains the urban-rural disaggregation, this is informed from UN WUP estimate of the proportion of the population living in urban areas. Pixels are assigned to be “urban” in descending order of population density until the implied national urban population total for that year is reached. Remaining pixels are classified as rural. Population at risk variables are defined as the population in areas with Plasmodium falciparum, Plasmodium vivax or either prevalence >0% in year 2000.

### Sources
`r un_badge()`
`r worldpop_badge()`
`r map_badge()`

## Model input demography

`site_file$population$demography`

Model input demography parameters

### Variables

`age_lower` Age lower bound (years)  
`age_upper` Age upper bound (years)  
`qx` The probability that an individual aged x dies before reaching age x  
`population` Population  
`population_proportion` Proportion of the total population in the designated age group  
`adjusted_mortality_rates` Mortality rates adjusted to retain age-structure in a modelled population of constant size  

### Description

Model-input demography is adjusted because the model population size is constant over time. This adjustment preserves the time-varying age structure implied by UN WPP within a constant-size model population, and is performed using the [peeps R package](https://github.com/mrc-ide/peeps).

### Sources

`r un_badge()`

⚠️ **Warning:** For all external and post-processing work the `site_file$population$population_by_age` should be used for age-disaggregated outputs.
