---
title: "Seasonality"
output: rmarkdown::html_vignette
link-citations: true
vignette: >
  %\VignetteIndexEntry{Seasonality}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(site)
```

## Seasonality

`site_file$seasonality$monthly_rainfall`

Monthly rainfall estimates

### Variables
`month` Month integer  
`month_name` Month  
`t` Midpoint of month  
`rainfall` Monthly rainfall estimate (mm)

### Description

Monthly rainfall global rasters aggregated to the site by taking the population at risk weighted mean rainfall across the region.

### Sources
`r chirps_badge()`

---

`site_file$seasonality$seasonality_parameters`

Fitted Fourier series seasonality parameters

### Variables
`g0, g1, g2, g3, h1, h2, h3` Fitted Fourier seasonality parameters

### Description
For each site we estimate the Fourier series parameters representing general seasonal profiles using the 
[umbrella R package](https://mrc-ide.github.io/umbrella/).

---

`site_file$seasonality$fourier_prediction`

A prediction of the seasonal curve using the estimated parameters

### Variables
`t` Day of the year  
`profile` Fourier estimate

### Description
We do not currently include historical year-on-year variability in rainfall seasonality
into the model runs so Fourier seasonal curves represent an average over all historical years in the rainfall
dataset.

---

`site_file$seasonality$peak_season`

Peak rainfall day

### Variables
`peak_season` Day of the year with peak rainfall (from fitted fourier)

### Description
Peak rainfall season is used to estimate timing of seasonally targeted interventions such as SMC and IRS.

